    name: Deploy Doggles
    on:
      push:
        branches:
          - master # check your repo, your default branch might be master!
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t bandzior/react-test -f ./client/Dockerfile.dev ./client
          - run: docker run -e CI=true bandzior/react-test npm test
     
          - run: docker build -t bandzior/doggles-client ./client
          - run: docker build -t bandzior/doggles-nginx ./nginx
          - run: docker build -t bandzior/doggles-server ./server
          - run: docker build -t bandzior/doggles-worker ./worker
     
          - run: docker push bandzior/doggles-client
          - run: docker push bandzior/doggles-nginx
          - run: docker push bandzior/doggles-server
          - run: docker push bandzior/doggles-worker
     
          - name: Generate deployment package
            run: zip -r deploy.zip . -x '*.git*'
     
          - name: Deploy to EB
            uses: einaregilsson/beanstalk-deploy@v18
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
              application_name: doggles
              environment_name: Doggles-env
              existing_bucket_name: elasticbeanstalk-eu-north-1-233587995725
              region: eu-north-1
              version_label: ${{ github.sha }}
              deployment_package: deploy.zip
